### ISSUE TITLE
Support node-sass ^4.0.0

### ISSUE THREAD

**Issue by ferdbold** [amercier/karma-scss-preprocessor#62]
Hi, [node-sass](https://github.com/sass/node-sass) 4.0.0 got released about two weeks ago, any updates on when this package will update its peer dependency to support the new versions?

Thanks!

**Comment by CSchulz** [comment]
@amercier Is the project dead?

**Comment by amercier** [comment]
@CSchulz Sorry, I have been away from my computer the last 8 months. I guess it's time for me to go back into business, starting with merging #63 then work on this one.

**Comment by amercier** [comment]
Fixed in version 3.0.0
