### ISSUE TITLE
karma-scss-preprocessor not installing anymore because of deleted npm dependency

### ISSUE THREAD

**Issue by temyrrian-dev** [amercier/karma-scss-preprocessor#69]
Hello, Alex, recently npm delete malicious package  flatmap-stream@0.1.1. 
And your  karma-scss-preprocessor has this dependency. Therefor  your package can`t install

**Comment by amercier** [comment]
Hi @temyrrian-dev, thanks for reporting!

Let me have a look.

**Comment by amercier** [comment]
I just released `karma-scss-preprocessor` version 4.0.0, which ships with a bunch of dependency upgrades. **Please note that version 4 requires NodeJS 6 minimum, which is the oldest [maintained version of NodeJS](https://nodejs.org/en/about/releases/).**

Feel free to re-open if this doesn't solve the issue (I believe it should).
